import { Book } from './definitions'
export const initialBookSliceState: Array<Book> = [
  {
    name: 'To Kill a Mockingbird',
    price: '$10.99',
    category: 'Fiction',
    description: 'A classic novel by Harper Lee.',
    id: '1',
  },
  {
    name: 'The Great Gatsby',
    price: '$12.50',
    category: 'Fiction',
    description: "F. Scott Fitzgerald's masterpiece.",
    id: '2',
  },
  {
    name: '1984',
    price: '$9.99',
    category: 'Fiction',
    description: 'A dystopian novel by George Orwell.',
    id: '3',
  },
  {
    name: 'The Lord of the Rings',
    price: '$25.00',
    category: 'Fantasy',
    description: "J.R.R. Tolkien's epic fantasy series.",
    id: '4',
  },
  {
    name: 'Pride and Prejudice',
    price: '$8.75',
    category: 'Romance',
    description: 'A classic romance novel by Jane Austen.',
    id: '5',
  },
  {
    name: "Harry Potter and the Sorcerer's Stone",
    price: '$11.25',
    category: 'Fantasy',
    description: "The first book in J.K. Rowling's Harry Potter series.",
    id: '6',
  },
  {
    name: 'The Catcher in the Rye',
    price: '$9.50',
    category: 'Fiction',
    description: "J.D. Salinger's coming-of-age novel.",
    id: '7',
  },
  {
    name: 'The Hobbit',
    price: '$13.00',
    category: 'Fantasy',
    description: 'A fantasy novel by J.R.R. Tolkien.',
    id: '8',
  },
  {
    name: 'Brave New World',
    price: '$10.75',
    category: 'Fiction',
    description: 'A dystopian novel by Aldous Huxley.',
    id: '9',
  },
]
